### ISSUE TITLE
More intuitive link to editor

### ISSUE THREAD

**Issue by gsteinLTU** [webgme/user-management-page#85]
In class yesterday, we were introduced to WebGME. A few of the students seemed to have issues figuring out how to get to the editor after registering their account and being redirected to the user management homepage. There's an image that they're instructed to click, but either not everyone was reading the text of the page or they didn't know it was what the text referred to (outside of the text, there isn't much letting you know it's a link instead of a normal image).

We discussed a few options yesterday, such as a button in the navigation bar so it will be present on all pages, and/or a button/caption underneath the icon on the home page so it's more obvious what users need to do.

**Comment by pmeijer** [comment]
![image](https://user-images.githubusercontent.com/6518904/45440456-e8594100-b681-11e8-957f-1ff1e91f391d.png)

**Comment by pmeijer** [comment]
Closed by #87
